// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQSgaffA6_JbqhMXY1HKhL1tOkabOfqC4',
    appId: '1:34923241454:web:3161d1290de5bd5c1bb8ff',
    messagingSenderId: '34923241454',
    projectId: 'eco4u-d794c',
    authDomain: 'eco4u-d794c.firebaseapp.com',
    storageBucket: 'eco4u-d794c.appspot.com',
    measurementId: 'G-NZR92YESWG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfMQPugacdwRphUoW3ApOv6FTnSeP7GDk',
    appId: '1:34923241454:android:f71afae6d6e23e571bb8ff',
    messagingSenderId: '34923241454',
    projectId: 'eco4u-d794c',
    storageBucket: 'eco4u-d794c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChDfCubeNxtWTc1nnjc4e0vtWl6fqoTAM',
    appId: '1:34923241454:ios:b1a59749601eeed71bb8ff',
    messagingSenderId: '34923241454',
    projectId: 'eco4u-d794c',
    storageBucket: 'eco4u-d794c.appspot.com',
    iosClientId:
        '34923241454-o3am6luh514uehjb2hjjhso9ve485ft7.apps.googleusercontent.com',
    iosBundleId: 'com.example.foryou',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChDfCubeNxtWTc1nnjc4e0vtWl6fqoTAM',
    appId: '1:34923241454:ios:c35b6c3262cb4e8a1bb8ff',
    messagingSenderId: '34923241454',
    projectId: 'eco4u-d794c',
    storageBucket: 'eco4u-d794c.appspot.com',
    iosClientId:
        '34923241454-t5vmkc06ge7idkrvrfc3t7ikrjrnu1l1.apps.googleusercontent.com',
    iosBundleId: 'com.example.foryou.RunnerTests',
  );
}
