// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQSgaffA6_JbqhMXY1HKhL1tOkabOfqC4',
    appId: '1:34923241454:web:3161d1290de5bd5c1bb8ff',
    messagingSenderId: '34923241454',
    projectId: 'eco4u-d794c',
    authDomain: 'eco4u-d794c.firebaseapp.com',
    databaseURL: 'https://eco4u-d794c-default-rtdb.firebaseio.com',
    storageBucket: 'eco4u-d794c.appspot.com',
    measurementId: 'G-NZR92YESWG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfMQPugacdwRphUoW3ApOv6FTnSeP7GDk',
    appId: '1:34923241454:android:c39fd122c11bc0931bb8ff',
    messagingSenderId: '34923241454',
    projectId: 'eco4u-d794c',
    databaseURL: 'https://eco4u-d794c-default-rtdb.firebaseio.com',
    storageBucket: 'eco4u-d794c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChDfCubeNxtWTc1nnjc4e0vtWl6fqoTAM',
    appId: '1:34923241454:ios:b5a4206248dc0ffa1bb8ff',
    messagingSenderId: '34923241454',
    projectId: 'eco4u-d794c',
    databaseURL: 'https://eco4u-d794c-default-rtdb.firebaseio.com',
    storageBucket: 'eco4u-d794c.appspot.com',
    iosBundleId: 'com.example.snapDeals',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChDfCubeNxtWTc1nnjc4e0vtWl6fqoTAM',
    appId: '1:34923241454:ios:b5a4206248dc0ffa1bb8ff',
    messagingSenderId: '34923241454',
    projectId: 'eco4u-d794c',
    databaseURL: 'https://eco4u-d794c-default-rtdb.firebaseio.com',
    storageBucket: 'eco4u-d794c.appspot.com',
    iosBundleId: 'com.example.snapDeals',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBptt16hin1mgpWJDV928p5ZsF2jisEIfo',
    appId: '1:34923241454:web:8670933e3390b65d1bb8ff',
    messagingSenderId: '34923241454',
    projectId: 'eco4u-d794c',
    authDomain: 'eco4u-d794c.firebaseapp.com',
    databaseURL: 'https://eco4u-d794c-default-rtdb.firebaseio.com',
    storageBucket: 'eco4u-d794c.appspot.com',
    measurementId: 'G-5Y5F044MF2',
  );

}